---
abstract: unknown
author:
  - 'Jay Kuri (jayk) C<< <jayk@cpan.org> >>.'
  - 'Jay Kuri <jayk@cpan.org>'
build_requires:
  Catalyst::Runtime: 5.90051
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
  Try::Tiny: 0
configure_requires:
  CPAN::Meta: 0
  ExtUtils::MakeMaker: 6.59
dynamic_config: 0
generated_by: 'Module::Install version 1.06, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-SimpleAPI
no_index:
  directory:
    - inc
    - t
requires:
  JSON::Any: 0
  namespace::autoclean: 0
  perl: v5.10.0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/ywatase/CatalystX-SimpleAPI.git
version: 0.05
